/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
        /**
          * Size of input
         */
        "size": number;
    }
    interface WrapperMyComponent {
        "size": number;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLWrapperMyComponentElement extends Components.WrapperMyComponent, HTMLStencilElement {
    }
    var HTMLWrapperMyComponentElement: {
        prototype: HTMLWrapperMyComponentElement;
        new (): HTMLWrapperMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "wrapper-my-component": HTMLWrapperMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
        /**
          * Size of input
         */
        "size"?: number;
    }
    interface WrapperMyComponent {
        "size"?: number;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "wrapper-my-component": WrapperMyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "wrapper-my-component": LocalJSX.WrapperMyComponent & JSXBase.HTMLAttributes<HTMLWrapperMyComponentElement>;
        }
    }
}
